### PR TITLE
Update to use latest opentracing and grpc

### PR DESCRIPTION
**Pull request by matthewrj**
Update to use opentracing 0.30.0 and grpc 1.6.1

### CODE REVIEW

**Comment by hzariv** [comment]
Why is nobody merging this PR? (without this upgrade this artifact is pretty useless)

**Comment by hzariv** [comment]
@bhs this is blocking us from upgrading gRPC and opentracing versions in our project. Could someone review and merge this PR?

**Comment by bhs** [comment]
@hzariv sorry – my inbox is an absolute maze regarding Github (literally hundreds of repos sending me mail, which has led me to give up unless I'm `@bhs`'d).

I will take a look and most likely rubberstamp. Sorry.

**Review by bhs — APPROVED** [review]
Seems like an improvement. Apologies again for the delay.

If you'd like to be an owner in this repo, let me know... couldn't do a slower job than I've done!! :-/

**Comment by hzariv** [comment]
Thanks a lot @bhs for quick merge. I don't mind to be an owner to speed up review and merge. I might need help with build and release of this artifacts as I am new to gradle.

**Comment by bhs** [comment]
@hzariv https://github.com/grpc-ecosystem/grpc-opentracing/invitations

**Pull request merged**
